# Generated by Django 3.1.7 on 2021-05-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='title',
        ),
    ]
