# Generated by Django 3.1.7 on 2021-05-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0003_auto_20210502_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
