# Generated by Django 3.1.7 on 2021-05-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0004_auto_20210502_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.TextField(),
        ),
    ]
