# Generated by Django 3.1.7 on 2021-05-02 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0005_auto_20210502_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='lastEdited',
        ),
    ]
