# Generated by Django 3.1.7 on 2021-05-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0007_auto_20210503_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='creationDate',
            new_name='lastEdited',
        ),
    ]
